local-pv-provisioner: v0.2.12
cybozu/neco-containers pull request #1211
Opened 2024-01-29 11:52 UTC by daichimukai

Release local-pv-provisioner v0.2.12 that supports kubernetes v1.28.

2024-01-29 23:34 UTC, daichimukai commented on local-pv-provisioner/local-pv-provisioner.yaml
> +          image: quay.io/cybozu/local-pv-provisioner:0.2.12
I forgot to update the version here when we released v0.2.11.

2024-01-30 00:58 UTC, llamerada-jp commented
Versions written in Makefile should be updated.
https://github.com/cybozu/neco-containers/blob/935a9c33b6905dc530136b59f2dcbef4fa9d10b4/local-pv-provisioner/Makefile#L5-L6

2024-01-30 00:59 UTC, llamerada-jp requested changes
Versions written in Makefile should be updated.
https://github.com/cybozu/neco-containers/blob/935a9c33b6905dc530136b59f2dcbef4fa9d10b4/local-pv-provisioner/Makefile#L5-L6

2024-01-30 01:24 UTC, daichimukai commented
> Versions written in Makefile should be updated.
> 
> https://github.com/cybozu/neco-containers/blob/935a9c33b6905dc530136b59f2dcbef4fa9d10b4/local-pv-provisioner/Makefile#L5-L6

Thank you. Fixed.
https://github.com/cybozu/neco-containers/compare/79bc1d4b5b937810b777983a7440e1d1d9120597..60d07a028295f979c2218e35110647e6feef52e9

2024-01-30 01:26 UTC, llamerada-jp approved these changes

2024-01-30 01:27 UTC, merged