argcd vup 2.9
cybozu/neco-containers pull request #1220
Opened 2024-02-08 06:51 UTC by takara9

ArgoCD 2.9 のコンテナを準備するためです。最終的に2.10まで上げます。

2024-02-08 09:14 UTC, morimoto-cybozu requested changes
[maintenance.md](https://github.com/cybozu/neco-containers/blob/main/maintenance.md#argocd)に書かれた手順を実施してください。
TAGファイルの更新だけで済む場合もありますが、それはDockerfile等を更新する必要がなくてそのDockerfileのまま再ビルドすればおしまい、という特殊例ですね。

「TAG, BRANCHに書かれたバージョンに基づいてDockerfileも自動的に更新するぞ！」という仕組みがあると便利なのですが、upstreamのDockerfileが劇的に変化することもあるので難しそうです。

Neco Wikiの"Procedures - Regular Update"に書かれた内容、特に「neco-containersの更新」や「neco-appsの更新」の項目を確認しておくと流れが分かるかと思います。
「ビルドに使うGoのバージョンも上げよう」といった情報も書かれていますし。

2024-02-08 13:10 UTC, morimoto-cybozu commented
> 「TAG, BRANCHに書かれたバージョンに基づいてDockerfileも自動的に更新するぞ！」という仕組みがあると便利なのですが、upstreamのDockerfileが劇的に変化することもあるので難しそうです。

完全に自動で追随するのは無理なので「とりあえずupstreamのビルド手順に大きな変化がない仮定でTAGに合うように自動更新して、pull requestを作って、そのコメントにupstreamの新旧Dockerfileの差分を貼る」とか？
元ネタがDockerfileではなくMakefileだったりもして、どのupstreamにも対応した汎用ツールとはしづらいですが。

いずれにせよこのタスクでは手作業でDockerfile内のバージョン表記を編集しましょう。

2024-02-13 07:06 UTC, takara9 commented
@morimoto-cybozu 
先ほどは、親切なご説明をありがとうございました。ご指導に従って更新して、CIが通過しました。
KUSTOMIZE_VERSION も 5.2.1へ変更した方が良ければ、対応しますので、ご指示頂ければ幸いです。

2024-02-13 14:00 UTC, morimoto-cybozu requested changes
argocdの方の更新はこれでOKです。
Dockerfileやdex, redis, haproxyについては更新不要ということで。

`admission/Makefile`の`KUSTOMIZE_VERSION`はこのままとしてください。
`CONTROLLER_TOOLS_VERSION`とあわせ、K8s更新への対応の際に更新します。

`admission/TAG`を更新してください。
admissionのコンテナイメージを更新し、Argo CD 2.9のApplicationオブジェクトを間違いなく扱うためです。
(admissionのロジックで扱うフィールドではありませんが一部フィールドが増えており、admissionが古いところに新しいオブジェクトが来るとエラーになるかもしれません。
前方互換性のために知らないフィールドは静かに無視する可能性もありますが。)
自前のソフトウェアなので4桁目ではなく3桁目を上げることになります。

2024-02-13 14:00 UTC, morimoto-cybozu commented on admission/Makefile
> +CONTROLLER_TOOLS_VERSION = 0.14.0
このバージョンは更新不要です。

2024-02-14 00:09 UTC, takara9 commented on admission/Makefile
> +CONTROLLER_TOOLS_VERSION = 0.14.0
間違えました。ご確認ありがとうございます。

2024-02-14 00:12 UTC, takara9 commented
@morimoto-cybozu 
ご確認いただき、ありがとうございます。２点修正しました。

2024-02-14 00:15 UTC, takara9 commented on admission/Makefile
> +CONTROLLER_TOOLS_VERSION = 0.14.0
argocd v2.9 -> v2.10 で redis 7.0.11 -> 7.0.14 へ更新になりますので、あらためて、レビュー頂ければ幸いです。

2024-02-14 02:14 UTC, morimoto-cybozu commented
@takara9 
変更内容はこれで良くなったと思います。
Circle CIのworkflow "main"が失敗しており、今回の変更以前からの問題とみられるため状況を確認しています。
こちらで修正するなり、ほかで修正後にrebaseするなりが必要になりそうです。

2024-02-14 03:53 UTC, takara9 commented
@morimoto-cybozu 
ご確認ありがとうございます。
必要であれば、こちらでも対応しますので、ご指示頂けると幸いです。

2024-02-14 04:14 UTC, takara9 commented
@morimoto-cybozu 
こちらでも調べてみました。このリンクによると、Makefileの中で、相対パスが利用できないようです。
こちらで修正して試してみても良いですか？
https://tex2e.github.io/blog/makefile/import-another-makefile

2024-02-14 06:59 UTC, takara9 commented
@morimoto-cybozu 
先ほどは、Zoomで会話いただき、ありがとうございました。
言われるとおりに、rebaseしたら、CIが通過しました。
squash してから 再レビュー依頼を出させて頂きます。

2024-02-14 07:30 UTC, morimoto-cybozu commented
@takara9 
admissionの方でcontourに関する更新が同時期にmainに入った影響で、おかしなことになっています。
* `admission/Makefile`の`CONTOUR_VERSION`を戻してしまっている
* `admission/TAG`が最終的に更新されていない

2024-02-14 07:55 UTC, morimoto-cybozu approved these changes

2024-02-14 08:56 UTC, merged