local-pv-provisioner: support Filesystem PV
cybozu/neco-containers pull request #1388
Opened 2024-07-23 07:36 UTC by ushitora-anqou

2024-08-06 01:41 UTC, satoru-takeuchi commented
@ushitora-anqou Please update [README.md](https://github.com/cybozu/neco-containers/blob/main/local-pv-provisioner/README.md) too.

2024-08-06 09:10 UTC, ushitora-anqou commented
I added two commits:

- The first one is to update README.md. Please see the commit message for the details.
- The second one is to update the code to handle `LP_NAMESPACE` correctly.

2024-08-07 12:16 UTC, satoru-takeuchi requested changes
Today's review results. 70% of the work is still left.

2024-08-07 12:16 UTC, satoru-takeuchi commented on local-pv-provisioner/controllers/device_detector.go
> +	lppAnnotPrefix           = "local-pv-provisioner.cybozu.io/"
How about rename `lppAnnotPrefix` to `lppPrefix` or `lppDomain`? The main reason is that this prefix is used both for annotation and label (`lppAnnotNode`).

In addition, I suggest renaming `localPVProvisionerLabelKey` to `localPVProvisonerLegacyLabelKey` or `lppLegacyLabelKey`.

2024-08-07 12:16 UTC, satoru-takeuchi commented on local-pv-provisioner/controllers/device_detector.go
> +		return nil, errors.New("device-dir must be an absolute path")
```suggestion
		return nil, errors.New("deviceDir must be an absolute path")
```

2024-08-07 12:16 UTC, satoru-takeuchi commented on local-pv-provisioner/controllers/device_detector.go
> +		return nil, errors.New("device-dir is not a directory")
```suggestion
		return nil, errors.New("deviceDir is not a directory")
```

2024-08-07 12:16 UTC, satoru-takeuchi commented on local-pv-provisioner/controllers/device_detector.go
> +		return nil, fmt.Errorf("unable to compile device filter: %s: %w", pvSpecDeviceNameFilter, err)
```suggestion
		return nil, fmt.Errorf("unable to compile deviceFilter: %s: %w", pvSpecDeviceNameFilter, err)
```

2024-08-08 02:51 UTC, satoru-takeuchi requested changes
Progress:
[x] code
[ ] unit tests
[ ] e2e tests
[ ] README.md

2024-08-08 02:51 UTC, satoru-takeuchi commented on local-pv-provisioner/controllers/device_detector.go
> +		return
Please add a log to let users know why the remaining work was canceled.

2024-08-08 02:52 UTC, ushitora-anqou commented
Thank you for your feedback! I added 4 commits to fix my code:

- [c01b7d1](https://github.com/cybozu/neco-containers/pull/1388/commits/c01b7d1642158f387a058e880e6b892992157d76): This is a kaizen not related to your feedback.
- [866ca96](https://github.com/cybozu/neco-containers/pull/1388/commits/866ca96bd12de03ac00306ea750eb46d29860257): This commit renames `localPVProvisionerLabelKey` to `lppLegacyLabelKey`, as you suggested.
- [589065c](https://github.com/cybozu/neco-containers/pull/1388/commits/589065c58509d6899ac21514c9cf3f28bbe4e882): This commit fixes the roles and role bindings for the e2e tests, as you suggested.
- [1cca3ca](https://github.com/cybozu/neco-containers/pull/1388/commits/1cca3ca299b711aeb1c99fe4133a70ab23e57fc9): This commit renames `lppAnnotPrefix` to `lppDomain` and fixes the error messages, as you proposed.

2024-08-08 03:02 UTC, ushitora-anqou commented
The commit [08312da](https://github.com/cybozu/neco-containers/pull/1388/commits/08312daa7acd95d25399298e0aa2e1296a4ab4af) fixes the `doesConflict` name and its logging problem you pointed out.

2024-08-09 06:50 UTC, satoru-takeuchi requested changes

2024-08-09 06:50 UTC, satoru-takeuchi commented on local-pv-provisioner/e2etest/Makefile
> +	$(MINIKUBE) ssh $(DD) if=/dev/zero of=loop1.img bs=1G seek=1 count=0
```suggestion
	$(MINIKUBE) ssh -- $(DD) if=/dev/zero of=loop1.img bs=1G seek=1 count=0
```

Although the current code works as expected, it's better to add `--` as other lines.

2024-08-09 06:50 UTC, satoru-takeuchi commented on local-pv-provisioner/Makefile
> +	docker build . -t $(IMAGE_TAG_LATEST)
I guess `docker tag $(IMAGE_TAG) $(IMAGE_TAG_LATEST)` is enough.

2024-08-09 06:50 UTC, satoru-takeuchi commented on local-pv-provisioner/e2etest/ci-setup-kvm.sh
> +fi
These lines can be removed since the same check is done by `kvm-ok`.

2024-08-09 06:50 UTC, satoru-takeuchi commented on local-pv-provisioner/e2etest/ci-setup-kvm.sh
> +sudo modprobe -a kvm_amd
IIRC, kernel modules will be loaded on demand and we can remove these lines.

2024-08-09 07:45 UTC, satoru-takeuchi commented on local-pv-provisioner/e2etest/Makefile
> +	$(MAKE) -C .. docker
The docker image will be built in the minikube VM, correct? If so, you can build the image far faster by increasing VM resources like `--memory` and `--cpus`.

2024-08-13 02:17 UTC, ushitora-anqou commented on local-pv-provisioner/controllers/device_detector_test.go
> +				}, "2s", "1s").Should(Succeed())
When I wrote this test, I wanted to check that the created PVs weren't being removed unexpectedly. But it seems that this `Consistently` doesn't make sense anymore. I'll remove it.

2024-08-13 02:29 UTC, ushitora-anqou commented
@satoru-takeuchi Thank you for your feedback! I hope the following two commits should resolve your concerns:

- [5cf0410](https://github.com/cybozu/neco-containers/pull/1388/commits/5cf0410e463b90a59475c374ed7233d080ec7942): for `device_detector_test.go` and `suite_test.go`.
- [36c56a4](https://github.com/cybozu/neco-containers/pull/1388/commits/36c56a4ee0e29d187a0d8d68d3d48f776fb39946): for `Makefile` and `e2etest/*`.

2024-08-13 05:16 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits. I added WIP label to prevent merging by mistake.

2024-08-13 08:35 UTC, ushitora-anqou commented
@satoru-takeuchi I squashed my commits. Could you review and merge this PR? There should be no differences from before the squash. https://github.com/cybozu/neco-containers/compare/36c56a4ee0e29d187a0d8d68d3d48f776fb39946..447c024c386abdcf7a2e95342bdfb665c6fff04f

2024-08-14 00:31 UTC, merged