Develop bmc-log-collector
cybozu/neco-containers pull request #1432
Opened 2024-09-18 07:05 UTC by takara9

2024-09-27 09:08 UTC, masa213f requested changes

2024-09-27 09:08 UTC, masa213f commented on bmc-log-collector/log-pointer.go
> +			os.Remove(filePath)
Please check the error.

2024-09-29 23:55 UTC, takara9 commented on bmc-log-collector/bmc-user.go
> +	g, err := os.Open(userFile)
changed

2024-09-29 23:58 UTC, takara9 commented on bmc-log-collector/Makefile
> +GINKGO = $(HOME)/go/bin/ginkgo
Delete it.

2024-09-30 00:02 UTC, takara9 commented on bmc-log-collector/LICENSE
removed

2024-09-30 00:11 UTC, takara9 commented on bmc-log-collector/main.go
> +	flgScrapingIntervalTimer *int    = flag.Int("scraping-interval-timer", 300, "Timer(sec) of scraping interval time")
I don't think so,
but "time" is rather than "timer" due to "timer" may means device.

2024-09-30 00:20 UTC, takara9 commented on bmc-log-collector/main.go
> +	flag "github.com/spf13/pflag"
I reffered this pflag example. 
https://pkg.go.dev/github.com/spf13/pflag#pkg-overview

2024-09-30 05:08 UTC, takara9 commented on bmc-log-collector/log-pointer.go
> +	file, err := os.Create(filePath)
Impoved

2024-09-30 05:08 UTC, takara9 commented on bmc-log-collector/log-pointer.go
> +		f, err = os.Create(filePath)
Improved

2024-09-30 05:10 UTC, takara9 commented on bmc-log-collector/log-pointer.go
> +		// When other error occur
removed

2024-09-30 05:15 UTC, takara9 commented on bmc-log-collector/main.go
> +	configLc.password = user.Support.Password.Raw
Improved.

2024-09-30 05:16 UTC, takara9 commented on bmc-log-collector/log-collector.go
> +				bmcByteJsonLog, _ := json.Marshal(members.Sel[i])
changed

2024-09-30 05:20 UTC, takara9 commented on bmc-log-collector/log-pointer.go
> +	if json.Unmarshal(byteJSON, &lptr) != nil {
changed.

2024-09-30 05:20 UTC, takara9 commented on bmc-log-collector/Makefile
> +	rm -fr testdata/pointers_main_test
changed

2024-09-30 05:21 UTC, takara9 commented on bmc-log-collector/README.md
> +        ipv4:   "192.168.10.1" // Server IP address
fixed.

2024-09-30 05:22 UTC, takara9 commented on bmc-log-collector/README.md
> +Usage of ./bmc-log-collectorn:
fixed

2024-09-30 06:16 UTC, takara9 commented on bmc-log-collector/log-collector.go
> +		if lastPtr.LastError != err {
Improved

2024-09-30 06:35 UTC, takara9 commented on bmc-log-collector/log-pointer.go
> +			os.Remove(filePath)
fixed

2024-10-01 05:13 UTC, masa213f requested changes

2024-10-01 07:32 UTC, takara9 commented on bmc-log-collector/Makefile
> +.PHONY: clean
add line

2024-10-02 04:30 UTC, masa213f approved these changes
LGTM

2024-10-02 04:47 UTC, merged