Update GitHub Actions workflow for Go version updates
cybozu/neco-containers pull request #1442
Opened 2024-10-11 00:55 UTC by 012xx

This PR updates the Go version to the latest stable version using CI automation.

Updated files:
- `golang-all/golang-$go_major-$CODENAME/Dockerfile`
- `golang-all/golang-$go_major-$CODENAME/TAG`

e.g.)
- `golang-all/golang-1.23-jammy/Dockerfile`
- `golang-all/golang-1.23-jammy/TAG`
- `golang-all/golang-1.22-jammy/Dockerfile`
- `golang-all/golang-1.22-jammy/TAG`

2024-10-25 07:29 UTC, rkwmt requested changes

2024-10-25 08:06 UTC, 012xx commented on .github/workflows/update.yaml
> +          PR_TITLE="Update Go versions to $VERSIONS"
It was unintentional. Thank you for pointing this out🙏

2024-10-28 05:11 UTC, takahiro-yamada requested changes

2024-10-28 05:11 UTC, takahiro-yamada commented on .github/workflows/update.yaml
> +              CURRENT_TAG=$(cat "$TAG_PATH" | cut -d_ -f1)
`CURRENT_TAG` doesn't seem to be used.

2024-10-29 03:29 UTC, rkwmt commented on .github/workflows/update.yaml
> +          if [ "$(echo -e "$HIGHEST_MAJOR_VERSION\n$HIGHEST_CONFIGURED_VERSION" | sort -V | tail -n1)" = "$HIGHEST_MAJOR_VERSION" ] && [ "$HIGHEST_MAJOR_VERSION" != "$HIGHEST_CONFIGURED_VERSION" ]; t
I feel this code for checking newer versions is complex. To make it simpler, how about detecting only the differences between the stable versions of Go and the versions we specify in `GO_MAJOR_VERSIONS` ? For example, we could use the `diff` command and write something like this:

```shell
GO_MAJOR_VERSIONS="1.23 1.22"
GO_STABLE_MAJOR_VERSIONS="1.24 1.23"
diff <(printf "%s\n" ${GO_MAJOR_VERSIONS}) <(printf "%s\n" ${GO_STABLE_MAJOR_VERSIONS})
```

2024-10-30 05:17 UTC, rkwmt requested changes

2024-10-30 05:17 UTC, rkwmt commented on .github/workflows/update.yaml
> +              update_files "${go_major}" "${CODENAME}" "${LATEST_VERSION}"
`LATEST_VERSION` does not include a minor revision number, but it is compared to `GO_VERSION` which includes a minor revision number. I think this is unintended behavior, please fix.
https://github.com/cybozu/neco-containers/blob/4b958bc1b3c19f46e70fd80ac4277d9b7c7ffd71/.github/workflows/update.yaml#L58-L60

2024-11-01 08:18 UTC, rkwmt requested changes

2024-11-01 08:18 UTC, rkwmt commented on .github/workflows/update.yaml
> +              echo "${latest_version}_${codename}" > "${tag_path}"
The format of the TAG looks like `X.Y.Z.N-jammy`, where `X.Y.Z` is the Go version and N starts at 1 and increments. Therefore, it seems better to set it like `X.Y.Z.1_jammy` when updating.
https://github.com/cybozu/neco-containers/blob/8ce1748be91631f9cf478c22b17c06748abc04c4/golang-all/golang-1.22-jammy/TAG#L1

2024-11-07 01:12 UTC, takahiro-yamada approved these changes
LGTM

2024-11-07 07:11 UTC, merged