local-pv-provisioner: update go.mod
cybozu/neco-containers pull request #436
Opened 2020-09-17 07:40 UTC by kfyharukz

Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>

2020-09-17 08:06 UTC, kfyharukz commented on local-pv-provisioner/controllers/device_detector.go
> +func (dd *DeviceDetector) pvName(devPath string) string {
The receiver methods of DeviceDetector are just moved from `persisntet_volume.go`.

2020-09-17 08:07 UTC, kfyharukz commented on local-pv-provisioner/controllers/device_detector_test.go
> +package controllers
Just move the test for DeviceDetector to this file.

2020-09-17 08:58 UTC, ymmt2005 commented on local-pv-provisioner/controllers/persistent_volume.go
> +		_, err = file.Write(zeroBlock)
Call `file.Sync` to persist the filling data.

2020-09-17 08:58 UTC, ymmt2005 commented on local-pv-provisioner/controllers/persistent_volume.go
> +		_, err = file.Write(zeroBlock)
Of course, after the loop.

2020-09-17 09:00 UTC, ymmt2005 commented on local-pv-provisioner/controllers/persistent_volume.go
> +	file, err := os.OpenFile(path, os.O_RDWR, 0)
Why do you use `os.O_RDWR`?

2020-09-17 09:01 UTC, ymmt2005 commented on local-pv-provisioner/go.mod
> +	sigs.k8s.io/controller-runtime v0.6.2
Pleaes update this to v0.6.3

2020-09-18 02:51 UTC, ymmt2005 commented on local-pv-provisioner/controllers/persistent_volume.go
> +	file.Sync()
You must check error.

2020-09-18 08:02 UTC, ymmt2005 requested changes
Please fix as commented.

2020-09-18 08:29 UTC, ymmt2005 approved these changes
LGTM

2020-09-18 08:35 UTC, merged