Add container management procedure
cybozu/neco-containers pull request #450
Opened 2020-10-27 05:04 UTC by yokaze

Signed-off-by: Daichi Sakaue <daichi-sakaue@cybozu.co.jp>

2020-11-06 09:19 UTC, zoetrope commented on maintenance.md
> +- If build fails, consult the upstream `Dockerfile` to keep up with the content.
We have to check it all the time, not just when build fails.

2020-12-08 08:05 UTC, tapih requested changes

2020-12-08 08:05 UTC, tapih commented on maintenance.md
> +
I understand that both the Kubernetes badge and the regular update badge are not needed here, but it's better to write etcd is updated in a separated task.

2020-12-09 05:16 UTC, masa213f commented on maintenance.md
> +
I wrote in a different document.

2020-12-09 05:46 UTC, tapih approved these changes
LGTM

2020-12-09 05:51 UTC, merged