admission: Fix condition for min order in vnetworkpolicy.
cybozu/neco-containers pull request #497
Opened 2021-01-15 06:42 UTC by kfyharukz

Signed-off-by: Kazuhito MATSUDA <kazuhito.matuda@gmail.com>

2021-01-15 06:47 UTC, ymmt2005 commented
Update `TAGS` too.

2021-01-15 07:06 UTC, ymmt2005 requested changes

2021-01-15 07:06 UTC, ymmt2005 commented on admission/cmd/run.go
> -	wh.Register("/validate-projectcalico-org-networkpolicy", hooks.NewCalicoNetworkPolicyValidator(mgr.GetClient(), dec, 1000))
I don't like this change...
Please keep this line, and change elsewhere.

2021-01-15 07:06 UTC, ymmt2005 commented on admission/hooks/run_test.go
> +	wh.Register(calicoValidateWebhookPath, NewCalicoNetworkPolicyValidator(mgr.GetClient(), dec, 1001))
ditto

2021-01-15 07:06 UTC, ymmt2005 commented on admission/hooks/validate_networkpolicy_test.go
> +	It("should deny policy having order < 1001", func() {
ditto

2021-01-15 09:56 UTC, kfyharukz commented
I force-pushed because commits were cluttered.

2021-01-18 02:38 UTC, ymmt2005 approved these changes
LGTM

2021-01-18 02:38 UTC, merged