add image build for cilium, cilium-operator-generic and hubble-relay
cybozu/neco-containers pull request #668
Opened 2021-10-10 22:59 UTC by Hsn723

This PR adds image builds for cilium, cilium-operator-generic and hubble-relay.
As described in cybozu-go/neco#1777, cilium is built with cilium/cilium#17418 applied as a patch.

2021-10-11 05:09 UTC, ysksuzuki requested changes

2021-10-11 05:28 UTC, Hsn723 commented on cilium/Dockerfile
> +    && make build-container install-container-binary
I opted against since I figured we likely wouldn't need it. Do you think we'd need bash-completion?

2021-10-11 05:29 UTC, Hsn723 commented on cilium/Dockerfile
> +    && images/cilium/download-hubble.sh
Similarly to https://github.com/cybozu/neco-containers/pull/668#discussion_r725798139

2021-10-12 07:44 UTC, ysksuzuki requested changes

2021-10-12 07:44 UTC, ysksuzuki commented on cilium/Dockerfile
> +
Please add LICENSE file. We normally place it at `/usr/local/{package}/LICENSE`.
https://github.com/cybozu/neco-containers/blob/main/loki/Dockerfile#L15

2021-10-12 08:03 UTC, Hsn723 commented on cilium/Dockerfile
> +
Cilium's LICENSE file is generated via `make licenses-all` and outputted as `LICENSE.all`. I've renamed it to `LICENSE` and it should be present in the root directory. Should I move it somewhere else?

https://github.com/cybozu/neco-containers/pull/668/files#diff-0b79bade2224c25c613d2c961b50b4d7a57cbfb9ac9ed7f11316c833ed0f71f5R18-R19

2021-10-12 08:31 UTC, ysksuzuki commented on cilium/Dockerfile
> +
Oh I didn't notice that. Forget it.

2021-10-13 01:55 UTC, ysksuzuki approved these changes

2021-10-14 05:36 UTC, merged