[DNM] Add s3 bucket count metrics
cybozu/neco-containers pull request #804
Opened 2022-06-01 04:48 UTC by cupnes

issue: https://github.com/cybozu/csa/issues/30

2022-06-20 00:52 UTC, satoru-takeuchi requested changes

2022-06-20 00:52 UTC, satoru-takeuchi commented on ceph-extra-exporter/README.md
> +                labelKeys: ["<key for label.>", ...]
```suggestion
                labelKeys: ["<a key for a label.>", ...]
```

2022-06-20 00:52 UTC, satoru-takeuchi commented on ceph-extra-exporter/README.md
> +                jqFilter:   "<see below.>",
```suggestion
                jqFilter:   "<see "jqFilter> section",
```

2022-06-20 00:52 UTC, satoru-takeuchi commented on ceph-extra-exporter/README.md
> +```
このへんの実例を入れてあげるといいと思います。テストケースからコピペでいいと思います。

2022-06-20 04:50 UTC, cupnes commented on ceph-extra-exporter/collector_test.go
> +			// ceph_extra_rgw_bucket_stats_s3_object_count{bucket="session-log-bucket-3d9a7583-f11b-4186-b4bc-8bf84c85266"}
```suggestion
			// ceph_extra_rgw_bucket_stats_s3_object_count{bucket="session-log-bucket-3d9a7583-f11b-4186-b4bc-8bf84c852662"}
```

2022-06-20 04:50 UTC, cupnes commented on ceph-extra-exporter/collector_test.go
> +			// ceph_extra_rgw_bucket_stats_s3_object_count{bucket="loki-data-bucket-bedc5054-a90f-41b0-82f8-c077c2c3221"}
```suggestion
			// ceph_extra_rgw_bucket_stats_s3_object_count{bucket="loki-data-bucket-bedc5054-a90f-41b0-82f8-c077c2c32217"}
```

2022-06-20 07:30 UTC, daichimukai commented on ceph-extra-exporter/executer.go
> -	ce.update()
Should we delete this?

2022-06-20 07:30 UTC, daichimukai commented on ceph-extra-exporter/executer_test.go
> +						jqFilter:   ".[] | [{value: .pg_autoscale_mode, labels: [.pool_name]}]",
Is this jqFilter correct?

2022-06-20 07:30 UTC, daichimukai commented on ceph-extra-exporter/executer_test.go
> +						jqFilter:   ".[] | [{value: .do_not_exist, labels: [.pool_name]}]",
ditto

2022-06-28 05:05 UTC, llamerada-jp commented on ceph-extra-exporter/README.md
> +```
added

2022-06-29 02:29 UTC, llamerada-jp approved these changes

2022-06-29 02:29 UTC, merged