MySQL ARM images
cybozu/neco-containers pull request #945
Opened 2023-01-21 08:19 UTC by bells17

2023-01-26 13:13 UTC, morimoto-cybozu requested changes

2023-01-30 14:37 UTC, bells17 commented on .circleci/config.yml
> +              ${BRANCH_TAG_OPTION} \
@morimoto-cybozu Thank you. I fixed the points that you commented on.

2023-02-02 14:33 UTC, morimoto-cybozu commented
@bells17 
I added a commit under the following considerations:
* It would be good to test the structure of ARM64 container images too.
* We should test the structure also in the main branch because that branch publishes official container images.

Would you please review my commit?

I felt intimidated to trouble you with frequent change requests, so I added the commit by myself.
I'm so sorry if you feel disagreeable with my intrusive behavior.

2023-02-06 10:41 UTC, bells17 commented
@morimoto-cybozu Thank you for your improving my commits. your commit looks good to me!

2023-02-06 10:55 UTC, morimoto-cybozu approved these changes

2023-02-06 10:56 UTC, merged